version: "3"
services:
  app:
    container_name: app
    restart: always
    build: ./frontend
    ports:
      - "4000:4000"
    depends_on:
      - mongo
  client:
    container_name: client
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
    links:
      - app
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    expose:
      - "27017"
    volumes:
      - F:\Software\Docker\image\
    ports:
      - "27017:27017"

